version: 1
update_configs:
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"

    default_reviewers:
      - "S0AndS0"
    default_labels:
      - "dependencies"
      - "dependabot"

    commit_message:
      prefix: ":robot:"
